syscall:
	sudo cp -u syscalls-updated.h /build/linux-6.13.7/include/linux/syscalls.h
	sudo cp -u sys-updated.c /build/linux-6.13.7/kernel/sys.c
	sudo cp -u syscall_64-updated.tbl /build/linux-6.13.7/arch/x86/entry/syscalls/syscall_64.tbl